# Generated by Django 5.1.3 on 2024-11-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookPage', '0002_remove_bookinfo_image_id_alter_bookimage_book_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='公众号id')),
                ('name', models.CharField(max_length=20, verbose_name='公众号名称')),
                ('url', models.CharField(max_length=200, verbose_name='二维码链接')),
            ],
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='account_id',
            field=models.CharField(default=1, max_length=5000, verbose_name='公众号账户id'),
            preserve_default=False,
        ),
    ]
