# Generated by Django 5.1.3 on 2024-11-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookPage', '0004_rename_account_id_bookinfo_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='account_name',
            field=models.CharField(max_length=20, verbose_name='公众号名称'),
        ),
    ]
