# Generated by Django 5.1.3 on 2024-11-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookPage', '0005_alter_bookinfo_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='提取码id')),
                ('book_id', models.IntegerField(verbose_name='书id')),
                ('secret', models.CharField(max_length=20, verbose_name='公众号提取密码')),
                ('accessCode', models.BooleanField(default=False, verbose_name='提取码')),
            ],
        ),
    ]
