# Generated by Django 5.1.3 on 2024-11-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookPage', '0006_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='link',
            field=models.CharField(default='', max_length=500, verbose_name='提取链接'),
            preserve_default=False,
        ),
    ]
