# Generated by Django 5.1.3 on 2024-11-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookPage', '0007_accesscode_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='accessCode',
            field=models.CharField(max_length=20, verbose_name='提取码'),
        ),
    ]
