# Generated by Django 5.1.3 on 2024-11-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookPage', '0008_alter_accesscode_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='name',
            field=models.CharField(default='百度网盘', max_length=20, verbose_name='网盘名称'),
            preserve_default=False,
        ),
    ]
